### PR TITLE
Convert the two tar.gz files into versioned src files

### PR DESCRIPTION
**Pull request by rsignell-usgs**
@martalmeida , I simply unpacked the older tar and committed it, then unpacked the newer tar and committed it.  Then deleted the tar files since github allows you to download as zip.   I also added a readme based on your paper.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@martalmeida, any issues with this?

**Comment by rsignell-usgs** [comment]
@martalmeida , how about clicking that green "merge pull request" button!

**Comment by martalmeida** [comment]
@rsignell-usgs, sound fine, thanks. I am still figuring out how this all works :)

**Comment by rsignell-usgs** [comment]
@martalmeida , nice work!  Thanks!

**Pull request merged**
